#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2026 Red Hat
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = """
---
module: splunk_ai_correlation_search
short_description: Manage pre-built correlation searches for AI Factory alerts
description:
  - This module creates or updates pre-built correlation searches designed for
    AI Factory infrastructure monitoring and alerting.
  - Includes searches for GPU thermal events, model drift detection, InfiniBand
    fabric errors, and training job anomalies.
  - Correlation searches are created in Splunk Enterprise Security and generate
    notable events when conditions are met.
  - Tested against Splunk Enterprise Server with Splunk Enterprise Security installed.
version_added: "5.2.0"
options:
  name:
    description:
      - Name of the correlation search.
    type: str
    required: true
  search_type:
    description:
      - Pre-built search template type for AI Factory monitoring.
      - C(gpu_thermal) monitors GPU temperature thresholds and thermal throttling events.
      - C(model_drift) detects statistical drift in model inference outputs.
      - C(infiniband_errors) monitors InfiniBand fabric errors affecting GPU interconnect.
      - C(training_anomaly) detects anomalies in training job metrics (loss spikes, OOM events).
      - C(gpu_utilization) alerts on sustained low or high GPU utilization.
      - C(custom) allows specifying a custom SPL search string.
    type: str
    required: true
    choices:
      - gpu_thermal
      - model_drift
      - infiniband_errors
      - training_anomaly
      - gpu_utilization
      - custom
  search:
    description:
      - Custom SPL search string.
      - Required when C(search_type) is C(custom).
      - Ignored for pre-built search types.
    type: str
  threshold:
    description:
      - Numeric threshold for the correlation search.
      - For C(gpu_thermal), this is the temperature in Celsius (default 85).
      - For C(model_drift), this is the drift score threshold (default 0.15).
      - For C(gpu_utilization), this is the utilization percentage (default 10 for low, 95 for high).
    type: float
  severity:
    description:
      - Severity of notable events generated by this correlation search.
    type: str
    choices:
      - informational
      - low
      - medium
      - high
      - critical
    default: high
  metrics_index:
    description:
      - Name of the Splunk index containing AI Factory metrics.
    type: str
    default: ai_factory_metrics
  disabled:
    description:
      - Whether the correlation search is disabled.
    type: bool
    default: false
  cron_schedule:
    description:
      - Cron schedule for the correlation search.
    type: str
    default: "*/5 * * * *"
  app:
    description:
      - Splunk app context for the correlation search.
    type: str
    default: SplunkEnterpriseSecuritySuite
  state:
    description:
      - Whether the correlation search should exist or not.
    type: str
    choices:
      - present
      - absent
    default: present

author: Ansible Security Automation Team (@ansible-security)
"""

EXAMPLES = """
# Create a GPU thermal monitoring correlation search
- name: Deploy GPU thermal alert
  splunk.es.splunk_ai_correlation_search:
    name: "AI Factory - GPU Thermal Alert"
    search_type: gpu_thermal
    threshold: 85
    severity: critical
    metrics_index: ai_factory_metrics
    state: present

# Create a model drift detection search
- name: Deploy model drift detection
  splunk.es.splunk_ai_correlation_search:
    name: "AI Factory - Model Drift Detection"
    search_type: model_drift
    threshold: 0.15
    severity: high
    metrics_index: ai_factory_metrics
    cron_schedule: "*/15 * * * *"
    state: present

# Create an InfiniBand error monitoring search
- name: Deploy InfiniBand error alert
  splunk.es.splunk_ai_correlation_search:
    name: "AI Factory - InfiniBand Errors"
    search_type: infiniband_errors
    severity: critical
    state: present

# Create a training anomaly detection search
- name: Deploy training anomaly detection
  splunk.es.splunk_ai_correlation_search:
    name: "AI Factory - Training Anomaly"
    search_type: training_anomaly
    severity: high
    state: present

# Create a custom correlation search for GPU utilization
- name: Deploy custom GPU utilization alert
  splunk.es.splunk_ai_correlation_search:
    name: "AI Factory - Low GPU Utilization"
    search_type: gpu_utilization
    threshold: 10
    severity: medium
    state: present

# Create a custom SPL correlation search
- name: Deploy custom AI Factory search
  splunk.es.splunk_ai_correlation_search:
    name: "AI Factory - Custom Alert"
    search_type: custom
    search: >
      | mstats avg(dcgm_gpu_temp) as gpu_temp WHERE index=ai_factory_metrics
      by host gpu_id span=5m
      | where gpu_temp > 90
    severity: critical
    state: present

# Remove a correlation search
- name: Remove GPU thermal alert
  splunk.es.splunk_ai_correlation_search:
    name: "AI Factory - GPU Thermal Alert"
    search_type: gpu_thermal
    state: absent
"""

RETURN = """
correlation_search:
  description: The correlation search configuration after module execution.
  returned: always
  type: dict
  contains:
    before:
      description: The search state before module execution.
      type: dict
      returned: when search existed
    after:
      description: The search state after module execution.
      type: dict
      returned: always
  sample:
    before: null
    after:
      name: "AI Factory - GPU Thermal Alert"
      search_type: "gpu_thermal"
      threshold: 85
      severity: "critical"
      disabled: false
changed:
  description: Whether any changes were made.
  returned: always
  type: bool
  sample: true
msg:
  description: Message describing the result.
  returned: always
  type: str
  sample: "Correlation search created successfully"
"""
